server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://34.87.103.162:3306/twitter
    username: root
    password: "@dmin1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
    path: "/api-docs/swagger"
  swagger-ui:
    enabled: true
    path: "/api-docs/swagger-ui"