server:
  port: 8081
  servlet:
    context-path: /api/v1

keycloak:
  auth-server-url: http://localhost:28080
  realm: plc
  resource: phuoctruong
  principal-attribute: preferred_username
  bearer-only: true
  ssl-required: external
  cors: true
  use-resource-role-mappings: true